[package]
name = "rust-preprocess"
version = "1.1.0"
edition = "2024"
authors = ["Gruppe 23"]

[dependencies]
rayon = "1.5"
indicatif = "0.17"
regex = "1.5"
csv = "1.1"
once_cell = "1.10"
rust-stemmers = "1.2"
fxhash="0.2.1"
clap = { version = "4.0", features = ["derive"] }
rand = "0.9.0"